package id.zelory.komnum.constant;

public class HTMLContent
{
	public static String header = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n"
			+ "\n"
			+ "<html>\n"
			+ "<head>\n"
			+ "<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n"
			+ "<link type=\"text/css\" rel=\"stylesheet\" href=\"css/materialize.min.css\"\n"
			+ "\tmedia=\"screen,projection\" />\n"
			+ "<meta name=\"viewport\"\n"
			+ "\tcontent=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" />\n"
			+ "<title>Komputasi Numerik - Zelory</title>\n"
			+ "</head>\n"
			+ "\n"
			+ "<body>\n"
			+ "\t<nav class=\"teal lighten-1\" role=\"navigation\">\n"
			+ "\t<div class=\"container\">\n"
			+ "\t\t<div class=\"nav-wrapper\">\n"
			+ "\t\t\t<a id=\"logo-container\" href=\"/\" class=\"brand-logo\">Komputasi\n"
			+ "\t\t\t\tNumerik</a>\n"
			+ "\t\t\t<ul class=\"right\">\n"
			+ "\t\t\t\t<li><a href=\"https://play.google.com/store/apps/developer?id=Zelory\" target=\"blank\">Zelory</a></li>\n"
			+ "\t\t\t</ul>\n"
			+ "\n"
			+ "\t\t\t<ul id=\"nav-mobile\" class=\"side-nav\">\n"
			+ "\t\t\t\t<li><a href=\"#\">Zelory</a></li>\n"
			+ "\t\t\t</ul>\n"
			+ "\t\t\t<a href=\"#\" data-activates=\"nav-mobile\" class=\"button-collapse\"><i\n"
			+ "\t\t\t\tclass=\"mdi-navigation-menu\"></i></a>\n"
			+ "\t\t</div>\n"
			+ "\t</div>\n"
			+ "\t</nav>\n"
			+ "\n"
			+ "\t<div class=\"section no-pad-bot\" id=\"index-banner\">\n"
			+ "\t\t<div class=\"container\">\n"
			+ "\t\t\t<br> <br>\n"
			+ "\t\t\t<h1 class=\"header center orange-text\">Komputasi Numerik - KOMSI\n"
			+ "\t\t\t\tB</h1>\n"
			+ "\t\t\t<div class=\"row center\">\n"
			+ "\t\t\t\t<h5 class=\"header col s12 light\">Pilih persamaan yang tersedia\n"
			+ "\t\t\t\t\tdibawah, dan masukan nilai atau NIM yang harus didapatkan.</h5>\n"
			+ "\t\t\t</div>\n"
			+ "\t\t\t\n"
			+ "\t\t\t<form action=\"/app\" method=\"get\">\n"
			+ "\t\t\t\n"
			+ "\t\t\t<div class=\"row center\">\n"
			+ "\n"
			+ "\t\t\t\t<div class=\"col l6 s12\">\n"
			+ "\t\t\t\t\t<select name=\"pers\">\n"
			+ "\t\t\t\t\t\t<option value=\"\" disabled selected>Pilih Persamaan</option>\n"
			+ "\t\t\t\t\t\t<option value=\"1\">x^2 + e^x</option>\n"
			+ "\t\t\t\t\t\t<option value=\"2\">x ln(x)</option>\n"
			+ "\t\t\t\t\t\t<option value=\"3\">x^2 + x</option>\n"
			+ "\t\t\t\t\t\t<option value=\"4\">x^3 + x^2 + x</option>\n"
			+ "\t\t\t\t\t\t<option value=\"5\">x^3 + x</option>\n"
			+ "\t\t\t\t\t</select>\n"
			+ "\t\t\t\t</div>\n"
			+ "\n"
			+ "\t\t\t\t<div class=\"input-field col l6 s12\">\n"
			+ "\t\t\t\t\t<input id=\"nim\" type=\"text\" class=\"validate\" name=\"nim\"> <label\n"
			+ "\t\t\t\t\t\tfor=\"nim\">Masukan nilai atau NIM yang harus\n"
			+ "\t\t\t\t\t\tdidapatkan.</label>\n"
			+ "\t\t\t\t</div>\n"
			+ "\n"
			+ "\t\t\t</div>\n"
			+ "\t\t\t\n"
			+ "\t\t\t<div class=\"row center\">\n"
			+ "\n"
			+ "\t\t\t\t<div class=\"col l6 s12\">\n"
			+ "\t\t\t\t\t<select name=\"metode\">\n"
			+ "\t\t\t\t\t\t<option value=\"\" disabled selected>Pilih Metode</option>\n"
			+ "\t\t\t\t\t\t<option value=\"1\">Bagi dua</option>\n"
			+ "\t\t\t\t\t\t<option value=\"2\">Newton</option>\n"
			+ "\t\t\t\t\t</select>\n"
			+ "\t\t\t\t</div>\n"
			+ "\n"
			+ "\t\t\t\t<div class=\"input-field col l6 s12\">\n"
			+ "\t\t\t\t\t<input id=\"error\" type=\"text\" class=\"validate\" name=\"error\"> <label\n"
			+ "\t\t\t\t\t\tfor=\"error\">Masukan tingkat ketelitian, misal 0.5.</label>\n"
			+ "\t\t\t\t</div>\n"
			+ "\n"
			+ "\t\t\t</div>\n"
			+ "\t\t\t\n"
			+ "\t\t\t<div class=\"row center\">\n"
			+ "\t\t\t\t<button class=\"btn-large waves-effect waves-light orange\" type=\"submit\" >HITUNG</button>\n"
			+ "\t\t\t</div>\n"
			+ "\t\t\t</form>\n"
			+ "\t\t\t\n" + "\t\t\t\n";

	public static String headerHasil = "    <div class=\"row\">\n"
			+ "        <div class=\"col s12\">\n"
			+ "          <div class=\"card teal\">\n"
			+ "            <div class=\"card-content white-text\">\n"
			+ "              <span class=\"card-title\">Hasil : </span>\n";

	public static String content = "              <p>I am a very simple card. I am good at containing small bits of information.\n"
			+ "              I am convenient because I require little markup to use effectively.</p>\n";

	public static String footerHasil = "            </div>\n"
			+ "          </div>\n" + "        </div>\n" + "            \n"
			+ "\t\t</div>\n";

	public static String footer = "\t</div>\n\t<footer class=\"page-footer teal\">\n"
			+ "\t<div class=\"container\">\n"
			+ "\t\t<div class=\"row\">\n"
			+ "\t\t\t<div class=\"col l9 s12\">\n"
			+ "\t\t\t\t<h5 class=\"white-text\">Tentang</h5>\n"
			+ "\t\t\t\t<p class=\"grey-text text-lighten-4\">Sebuah aplikasi web\n"
			+ "\t\t\t\t\tsederhana yang dibuat untuk membantu menyelesaikan tugas-tugas\n"
			+ "\t\t\t\t\tKomputasi Numerik - Komsi Kelas B 2015.</p>\n"
			+ "\n"
			+ "\n"
			+ "\t\t\t</div>\n"
			+ "\n"
			+ "\t\t\t<div class=\"col l3 s12\">\n"
			+ "\t\t\t\t<h5 class=\"white-text\">Temukan</h5>\n"
			+ "\t\t\t\t<ul>\n"
			+ "\t\t\t\t\t<li><a class=\"white-text\" href=\"https://www.facebook.com/zetbaitsu\" target=\"blank\">Facebook</a></li>\n"
			+ "\t\t\t\t\t<li><a class=\"white-text\" href=\"https://twitter.com/Zetbaitsu\" target=\"blank\">Twitter</a></li>\n"
			+ "\t\t\t\t\t<li><a class=\"white-text\" href=\"https://id.linkedin.com/pub/zetra/66/7b4/324\" target=\"blank\">Linkedin</a></li>\n"
			+ "\t\t\t\t\t<li><a class=\"white-text\" href=\"https://github.com/zetbaitsu\" target=\"blank\">Github</a></li>\n"
			+ "\t\t\t\t</ul>\n"
			+ "\t\t\t</div>\n"
			+ "\t\t</div>\n"
			+ "\t</div>\n"
			+ "\t<div class=\"footer-copyright\">\n"
			+ "\t\t<div class=\"container\">\n"
			+ "\t\t\tDikembangkan oleh <a class=\"teal-text text-lighten-3\"\n"
			+ "\t\t\t\thref=\"https://play.google.com/store/apps/developer?id=Zelory\" target=\"blank\">Zelory</a>\n"
			+ "\t\t\t\t&copy 2015.\n"
			+ "\t\t</div>\n"
			+ "\t</div>\n"
			+ "\t</footer>\n"
			+ "\n"
			+ "\t<script src=\"https://code.jquery.com/jquery-2.1.1.min.js\"></script>\n"
			+ "\t<script src=\"js/materialize.js\"></script>\n"
			+ "\t<script src=\"js/init.js\"></script>\n" + "\n" + "</body>\n"
			+ "</html>\n";
}
